title: "Daniel SÃ¡nchez OrdÃ³Ã±ez"
description: >
  PhD Candidate, Paris School of Economics<br>
  <a href="assets/cv_SANCHEZ_ORDONEZ.pdf">ðŸ“„ CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">ðŸ“§ Email</a> 
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
include:
  - assets/css
